[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
log = {workspace = true}
axum = "0.8.3"
lazy_static = "1.5.0"
tokio = { workspace = true, features = ["full"] }
axum-embed = "0.1.0"
rust-embed = "8.6.0"
